### ISSUE TITLE
Can I run this with OpenFaaS / open-source FaaS?

### ISSUE THREAD

**Issue by alexellis** [FutureSharks/invokust#12]
Would I be able to run this on OpenFaaS' Python runtime?

https://github.com/openfaas-incubator/python3-debian

I can do a build following the instructions but it seems to reach out to a Lambda/AWS region.

**Comment by FutureSharks** [comment]
I don't know what that is but you can simply use the first example:
https://github.com/FutureSharks/invokust#examples
This doesn't use Lambda.

**Comment by alexellis** [comment]
It's Serverless FaaS but open-source (rather than proprietary/cloud-hosted). This is what I managed to put together - https://github.com/alexellis/locust-openfaas

What do you think?

**Comment by FutureSharks** [comment]
I see, interesting! Looks OK but using `subprocess` is a bit hacky for something that is supposed to be serverless?

If I was you, in `locust/index.py`, I would copy the code from my example and then return/print the stats.

**Comment by FutureSharks** [comment]
> Creating a subprocess via the handler doesn't make it any more or less serverless.
OK fair enough 👍 

> I couldn't find out how to launch locust without using their binary / helper
That is exactly what this project does, as per the first example.

> I think I tried your code last night but it had a boto3 or Lambda session reference somewhere that stopped it from working.
If you be specific, I'd be happy to help!

>Have you tried locust/index.py in a regular Docker container for instance?
Nope.

**Comment by alexellis** [comment]
```
Traceback (most recent call last):
  File "index.py", line 1, in <module>
    import invokust
  File "/usr/local/lib/python3.6/site-packages/invokust/__init__.py", line 5, in <module>
    from .aws_lambda import get_lambda_runtime_info
  File "/usr/local/lib/python3.6/site-packages/invokust/aws_lambda/__init__.py", line 4, in <module>
    from .lambda_load_test import LambdaLoadTest
  File "/usr/local/lib/python3.6/site-packages/invokust/aws_lambda/lambda_load_test.py", line 17, in <module>
    client = session.client('lambda', config=config)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 73, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by alexellis** [comment]
Btw I also saw you have an interest in RPi - OpenFaaS also runs natively on Raspberry Pi and 64-bit ARM.

Let me know if you can push a fix up for testing that doesn't try to load boto and all that other Lambda stuff.

**Comment by FutureSharks** [comment]
Thanks!

I'll definitely fix it. Your use case sounds interesting. But it will take me a few days as I have little free time right now.

In the mean time, as a workaround for you, you can set an env var `AWS_DEFAULT_REGION=eu-west-1` to stop the error.

**Comment by FutureSharks** [comment]
Hi @alexellis could you test this PR and see if it solves the problem for you?
https://github.com/FutureSharks/invokust/pull/14

**Comment by FutureSharks** [comment]
Any update on this issue?

**Comment by alexellis** [comment]
This is as far as I got - https://github.com/alexellis/locust-openfaas

**Comment by FutureSharks** [comment]
>Would you be willing to spend a bit of time on it?

Spend more time on what? I fixed your issue in PR 14: https://github.com/FutureSharks/invokust/pull/14
I'm waiting for you to test it.
